version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
      - 9701:8080
  netdata:
    image: netdata/netdata
    expose:
      - "19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  v2ray1:
    image: v2ray/official:latest 
    volumes:
      - /etc/v2ray:/etc/v2ray
  v2ray2:
    image: v2ray/official:latest 
    volumes:
      - /etc/v2ray:/etc/v2ray



  update:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: v2ray/official netdata/netdata
